### ISSUE TITLE
Put in old events as posts

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-articles#7]
**Description**

Put in old events as posts.

**Comment by mgcth** [comment]
If you put in the date of the event under the post date I can also filter by upcoming and previous that way.

**Comment by docNord** [comment]
I can give it a shot, sure. How are they to be filed?

**Comment by mgcth** [comment]
Just create a new markdown file for each event, as you would a normal post. Just give it category: Event and date: Actual date of event.

Put up a PR and I can have a look at it :)
